Codelatin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static # carga de archivos estaticos de las configuraciones de URL (old-school)
from django.conf import settings 

from . import views

# app_name = 'categorias' - esto sirve cuando se quiere acceder a una vista desde otra app

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', inicio, name='inicio'),
    path('', include('home.urls')),
    path('tienda/', include('tienda.urls')),
    path('auths/', include('auths.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auths/urls.py
from django.urls import path
from . import views

app_name = 'auths'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate_account/<uidb64>/<token>/', views.verify_account, name='activate_account'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('categoria/<slug:categoria_slug>/', views.productos_por_categoria, name='productos_por_categoria'),
    path('categoria/producto/<slug:producto_slug>/', views.detalle_producto, name='detalle_producto'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import get_object_or_404, render
from tienda.models import Producto
from categorias.models import Categoria

# Create your views here.
def home(request):
    productos = Producto.objects.all().filter(disponible=True)
    categoria = Categoria.objects.first()
    print(categoria.get_url())
    context = {"productos": productos}

    return render(request, 'home/home.html', context)

home/templates/home/include/footer.html
<footer>
    <div class="footer-content">
        <p>&copy; 2025 Muyu Toys. Todos los derechos reservados.</p>
    </div>
</footer>

home/templates/home/include/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'home/css/navbar.css' %}" />
<nav class="navbar">
	<div class="nav-container">
		<a href="#" class="logo">
			<div class="logo-icon">🛒</div>
			<span class="logo-text">Muyu</span>
		</a>

		<div class="search-bar">
				<select class="search-select" id="searchCategory">
					<option value="all">Todas las categorías</option>
					{% for categoria in links %}
						<option value="{{ categoria.get_url }}">{{ categoria.nombre }}</option>
					{% endfor %}
				</select>
			<input
				type="text"
				class="search-input"
				id="text-buscar"
				placeholder="¿Qué estás buscando?"
			/>
			<button class="search-btn" id="btnBuscar">
				<span class="search-icon">🔍</span>
			</button>
		</div>

		<div class="hamburger" onclick="toggleMenu()">
			<span></span>
			<span></span>
			<span></span>
		</div>

		<ul class="nav-menu" id="navMenu">
			<li><a href="#nosotros" class="nav-link">Nosotros</a></li>
			<li><a href="{% url 'tienda:tienda' %}" class="nav-link">Tienda</a></li>
			<li><a href="#contacto" class="nav-link">Contacto</a></li>
			<div class="nav-buttons">
				{% if user.is_authenticated %}
				<span class="text-white bg-info px-2 rounded" style="height:20px">Hola, {{ user.username }}</span>
				<a href="{% url 'auths:logout' %}" class="btn btn-login">Logout</a>
				{% else %}
				<a href="{% url 'auths:login' %}" class="btn btn-login">Login</a>
				<a href="{% url 'auths:register' %}" class="btn btn-register">Registro</a>
				{% endif %}
				
			</div>
		</ul>
	</div>
</nav>

<div class="content">
	<h1>Bienvenido a Muyu Toys</h1>
	<img
		src="{% static 'home/images/muyu-sf.png' %}"
		alt="Banner de Juguetes"
		class="banner-image"
	/>
	<p>Tú Ecommerce de juguetes moderno con diseño responsive y profesional</p>
</div>

  <script>
    document.getElementById('btnBuscar').addEventListener('click', function() {
      const categoria = document.getElementById('searchCategory').value;
      // const texto = document.getElementById('txt-buscar').value.trim();
		console.log(categoria);
    if (categoria === "all") {
		window.location.href = "";
	} 
	else {
      // Redirigir a la página de resultados
      window.location.href = categoria;
    }
  });
  </script>